In [3]:
from unittest.mock import inplace

import torch


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print("Device name", torch.cuda.get_device_name(0))


GPU is available
Device name NVIDIA GeForce RTX 4060 Laptop GPU


# Creating a Tensor

In [4]:
h=torch.empty(2,3)

In [5]:
# check type
type(h)

torch.Tensor

In [7]:
# using zeros
ho=torch.zeros(2,3)
type(ho)

torch.Tensor

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(3,3)


tensor([[0.4651, 0.6748, 0.4246],
        [0.7949, 0.4537, 0.1734],
        [0.7151, 0.1187, 0.7459]])

In [17]:
# using random with seed
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [18]:
'''
One thing to remember is that seed is localized to a cell not like
sklearn's seed that works for the entire codefile
'''

"\nOne thing to remember is that seed is localized to a cell not like \nsklearn's seed that works for the entire codefile\n"

In [21]:
# using tensor custom
torch.tensor([[1,2,3],[3,3,4]])

tensor([[1, 2, 3],
        [3, 3, 4]])

# Tensor Shape


In [4]:
x= torch.tensor([[1,2,3],[3,3,4]])

In [6]:
x.shape

torch.Size([2, 3])

In [7]:
# ussi shape ka agar exact tensor banana ho toh

In [8]:
torch.empty_like(x)

tensor([[4182908080624,             0,             0],
        [            0,             0,             0]])

In [9]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [10]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [12]:
# torch.rand_like(x)
# // since rand generates float fooat values and here there are integer in x hence will generate error

In [15]:
y=torch.rand_like(x,dtype=torch.float)

# Mathematical operations

## scalar operations

In [17]:
x + y

tensor([[1.7467, 2.4458, 3.1866],
        [3.6144, 3.2692, 4.1297]])

In [22]:
x-2
x+2
x/2
# int division
((x*100)//3)%2

tensor([[1, 0, 0],
        [0, 0, 1]])

In [23]:
# the same can be done over two different tensors
x * y

tensor([[0.7467, 0.8916, 0.5598],
        [1.8433, 0.8075, 0.5190]])

In [24]:
x-y

tensor([[0.2533, 1.5542, 2.8134],
        [2.3856, 2.7308, 3.8703]])

In [25]:
x/y

tensor([[ 1.3393,  4.4862, 16.0778],
        [ 4.8825, 11.1449, 30.8303]])

In [26]:
torch.abs(x)
# Computes the absolute value of each element in input.

tensor([[1, 2, 3],
        [3, 3, 4]])

In [27]:
torch.round(y)

tensor([[1., 0., 0.],
        [1., 0., 0.]])

In [29]:
torch.ceil(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [30]:
torch.clamp(y,min=0,max=1
            )

tensor([[0.7467, 0.4458, 0.1866],
        [0.6144, 0.2692, 0.1297]])

# 3 Reduction Operation

In [1]:
import torch

In [5]:
torch.sum(x)

tensor(18)

In [6]:
torch.sum(x,dim=0)

tensor([ 5, 13])

In [7]:
torch.sum(x,dim=1)

tensor([12,  6])

In [9]:
# x=torch.rand_like(y,dtype=torch.float32)
x=torch.randint(size=(2,2),low=0,high=10,dtype=torch.float32)

In [10]:
x

tensor([[1., 6.],
        [7., 4.]])

In [12]:
torch.mean(x,dim=0)

tensor([4., 5.])

In [13]:
torch.median(x,dim=0)

torch.return_types.median(
values=tensor([1., 4.]),
indices=tensor([0, 1]))

In [18]:
torch.prod(x,dim=0)

tensor([ 7., 24.])

In [19]:
torch.std(x)

tensor(2.6458)

In [20]:
torch.var(x)

tensor(7.)

In [21]:
torch.argmax(x)

tensor(2)

In [22]:
torch.argmin(x)

tensor(0)

In [23]:
# matrix multiplication
torch.matmul(x,y)

tensor([[6.0093, 1.8303],
        [4.5010, 1.8897]])

In [25]:
# dot product
torch.dot(x,y)
# explicitly mentioned that can only work for 1D tensor

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [26]:
x

tensor([[1., 6.],
        [7., 4.]])

In [29]:
torch.transpose(x,1,0)

tensor([[1., 7.],
        [6., 4.]])

In [30]:
torch.inverse(x)

tensor([[-0.1053,  0.1579],
        [ 0.1842, -0.0263]])

In [31]:
# can also be done comparative functions also
# but not  doing here (>,<,!=,== etc)

In [32]:
torch.log(x)

tensor([[0.0000, 1.7918],
        [1.9459, 1.3863]])

In [33]:
torch.sigmoid(torch.log(x))

tensor([[0.5000, 0.8571],
        [0.8750, 0.8000]])

In [35]:
torch.softmax(x,dim=1)
# softmax can only be done for float

tensor([[0.0067, 0.9933],
        [0.9526, 0.0474]])

# Inplace

In [36]:
# kisi bhi operation ke aage _ laga do it becomes inplace
# like .add_, .relu_ etc


# Tensor operation in GPU

In [37]:
torch.cuda.is_available()

True

In [38]:
device=torch.device('cuda')

In [39]:
# creating a new tensor over GPU
torch.rand((2,3),device=device)

tensor([[0.4200, 0.6495, 0.1921],
        [0.1627, 0.9663, 0.7302]], device='cuda:0')

In [40]:
# moving existing tensor to GPU
a=torch.rand(2,3)

In [41]:
a.to(device)

tensor([[0.0020, 0.8469, 0.8578],
        [0.6446, 0.8917, 0.3542]], device='cuda:0')

In [43]:
a+5


tensor([[5.0020, 5.8469, 5.8578],
        [5.6446, 5.8917, 5.3542]])

In [2]:
# comparing the time of the cpu_exec and gpu_exec
import time
import torch

size=10000
device=torch.device('cuda')

matrix1=torch.randn(size,size)
matrix2=torch.randn(size,size)

start_timecpu= time.time()
result_cpu=torch.matmul(matrix1,matrix2)
end_timecpu= time.time() - start_timecpu
print(f"time on CPU: {end_timecpu:.2f} seconds")

# now running it into GPU

mat1=matrix1.to('cuda')
mat2=matrix2.to('cuda')

start_timegpu=time.time()
result_gpu=torch.matmul(mat1,mat2)
torch.cuda.synchronize()
end_timegpu=time.time() - start_timegpu


print(f"time on GPU: {end_timegpu:.2f} seconds")


# compare results
print('\n speedup cpu time/gpu time',end_timecpu/end_timegpu)

time on CPU: 1.82 seconds
time on GPU: 0.22 seconds

 speedup cpu time/gpu time 8.319613218166815
