In [1]:
import torch


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print("Device name", torch.cuda.get_device_name(0))


GPU is available
Device name NVIDIA GeForce RTX 4060 Laptop GPU


# Creating a Tensor

In [4]:
h=torch.empty(2,3)

In [5]:
# check type
type(h)

torch.Tensor

In [7]:
# using zeros
ho=torch.zeros(2,3)
type(ho)

torch.Tensor

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(3,3)


tensor([[0.4651, 0.6748, 0.4246],
        [0.7949, 0.4537, 0.1734],
        [0.7151, 0.1187, 0.7459]])

In [17]:
# using random with seed
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [18]:
'''
One thing to remember is that seed is localized to a cell not like
sklearn's seed that works for the entire codefile
'''

"\nOne thing to remember is that seed is localized to a cell not like \nsklearn's seed that works for the entire codefile\n"

In [21]:
# using tensor custom
torch.tensor([[1,2,3],[3,3,4]])

tensor([[1, 2, 3],
        [3, 3, 4]])